"""Add avatar_url to games table

Revision ID: 06e604ffc276
Revises: d8ce88a80c68
Create Date: 2025-11-27 13:14:59.921895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e604ffc276'
down_revision: Union[str, None] = 'd8ce88a80c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.add_column('games', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'avatar_url')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    # ### end Alembic commands ###
