"""Add new config sections

Revision ID: d8ce88a80c68
Revises: 5c25d516c465
Create Date: 2025-11-25 13:35:18.217712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ce88a80c68'
down_revision: Union[str, None] = '5c25d516c465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('game_core_config', sa.JSON(), nullable=True))
    op.add_column('configs', sa.Column('booster_config', sa.JSON(), nullable=True))
    op.add_column('configs', sa.Column('chapter_reward_config', sa.JSON(), nullable=True))
    op.add_column('configs', sa.Column('shop_config', sa.JSON(), nullable=True))
    op.drop_column('configs', 'game_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('game_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('configs', 'shop_config')
    op.drop_column('configs', 'chapter_reward_config')
    op.drop_column('configs', 'booster_config')
    op.drop_column('configs', 'game_core_config')
    # ### end Alembic commands ###
